#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Nazareno Lorenzo
url: "https://www.nazarenolorenzo.com.ar"
baseurl: ""
description: "Hey! I'm Naz, a Software Engineer based in Dublin, Ireland, with a passion for web related development. I started programming when I was 11 years old in JS+PHP+MySQL and I haven't stopped learning since then."

theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-48258624-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
